var explosion = {
   "type": "FeatureCollection",
   "features": [
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.8014,36.1171 ]
    },
    "properties": {
    "data_id":6078701,
    "iso":760,
    "event_id_cnty":"SYR61679",
    "event_id_no_cnty":61679,
    "event_date":"31 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Aleppo",
    "admin2":"Jebel Saman",
    "admin3":"Atareb",
    "location":"Jeineh",
    "geo_precision":1,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 31 May, 2019, an IED planted by an unidentified armed group in Jeineh in western Aleppo countryside detonated targeting an unidentified vehicle and leading to some wounded assumed to be civilian. No fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164580,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 40.9923,34.4322 ]
    },
    "properties": {
    "data_id":6046991,
    "iso":760,
    "event_id_cnty":"SYR61626",
    "event_id_no_cnty":61626,
    "event_date":"28 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Islamic State (Syria)",
    "assoc_actor_1":"",
    "inter1":2,
    "actor2":"QSD: Syrian Democratic Forces",
    "assoc_actor_2":"",
    "inter2":2,
    "interaction":22,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Deir-ez-Zor",
    "admin2":"Abu Kamal",
    "admin3":"Susat",
    "location":"Baghuz",
    "geo_precision":2,
    "source":"Liveuamap; SOHR",
    "source_scale":"Local partner-New media",
    "notes":"On 28 May 2019, a QSD fighter was killed by a landmine planted by Islamic State fighters in the Baghuz area",
    "fatalities":1,
    "timestamp":1571164400,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 40.4346,35.1248 ]
    },
    "properties": {
    "data_id":6082361,
    "iso":760,
    "event_id_cnty":"SYR61640",
    "event_id_no_cnty":61640,
    "event_date":"28 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"QSD: Syrian Democratic Forces",
    "assoc_actor_2":"",
    "inter2":2,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Deir-ez-Zor",
    "admin2":"Deir-ez-Zor",
    "admin3":"Basira",
    "location":"Zir",
    "geo_precision":1,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 28 May 2019, an IED planted by unidentified gunmen in a QSD vehicle in the town of Zir detonated, killing 1 QSD fighter and wounding others.",
    "fatalities":1,
    "timestamp":1571164585,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 41.2262,37.0447 ]
    },
    "properties": {
    "data_id":5913283,
    "iso":760,
    "event_id_cnty":"SYR61669",
    "event_id_no_cnty":61669,
    "event_date":"28 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":30,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Al-Hasakeh",
    "admin2":"Quamishli",
    "admin3":"Quamishli",
    "location":"Quamishli",
    "geo_precision":1,
    "source":"SOHR; SHAM",
    "source_scale":"Other-National",
    "notes":"On 28 May 2019, an IED planted by unidentified gunmen near a school in the city of Quamishli exploded with neither injuries nor fatalities reported.",
    "fatalities":0,
    "timestamp":1567462450,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 37.5149,36.3697 ]
    },
    "properties": {
    "data_id":6082503,
    "iso":760,
    "event_id_cnty":"SYR61668",
    "event_id_no_cnty":61668,
    "event_date":"28 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":30,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Aleppo",
    "admin2":"Al Bab",
    "admin3":"Al Bab",
    "location":"Al Bab",
    "geo_precision":1,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 28 May 2019, a VBIED parked in the town of Al Bab by unidentified gunmen detonated with neither injuries nor fatalities reported.",
    "fatalities":0,
    "timestamp":1571164585,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.77,36.2125 ]
    },
    "properties": {
    "data_id":6082776,
    "iso":760,
    "event_id_cnty":"SYR61676",
    "event_id_no_cnty":61676,
    "event_date":"28 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Idleb",
    "admin2":"Harim",
    "admin3":"Dana",
    "location":"Dana",
    "geo_precision":1,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 28 May 2019, a civilian was wounded when an IED placed in his vehicle in the town of Dana in Idleb province by unidentified gunmen detonated. No fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164585,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 37.5663,36.4337 ]
    },
    "properties": {
    "data_id":6080731,
    "iso":760,
    "event_id_cnty":"SYR61641",
    "event_id_no_cnty":61641,
    "event_date":"28 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Opposition Rebels (Syria)",
    "assoc_actor_2":"",
    "inter2":2,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Aleppo",
    "admin2":"Al Bab",
    "admin3":"Al Bab",
    "location":"Qabasin",
    "geo_precision":1,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 28 May 2019, an IED planted by unidentified gunmen in the vehicle of a rebel fighter in the town of Qabasin detonated with neither injuries nor fatalities reported.",
    "fatalities":0,
    "timestamp":1571164583,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 40.4277,35.158 ]
    },
    "properties": {
    "data_id":6046998,
    "iso":760,
    "event_id_cnty":"SYR61638",
    "event_id_no_cnty":61638,
    "event_date":"27 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"QSD: Syrian Democratic Forces",
    "assoc_actor_2":"",
    "inter2":2,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Deir-ez-Zor",
    "admin2":"Deir-ez-Zor",
    "admin3":"Basira",
    "location":"Basira",
    "geo_precision":1,
    "source":"Liveuamap; SOHR",
    "source_scale":"Local partner-New media",
    "notes":"On 27 May 2019, a booby-trapped motorcycle parked by unidentified gunmen next to the headquarters of the QSD military police in the town of Basira detonated, causing material damage and wounding a number of QSD fighters. No fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164400,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 40.7234,35.6677 ]
    },
    "properties": {
    "data_id":5842054,
    "iso":760,
    "event_id_cnty":"SYR61639",
    "event_id_no_cnty":61639,
    "event_date":"27 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"QSD: Syrian Democratic Forces",
    "assoc_actor_2":"",
    "inter2":2,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Al-Hasakeh",
    "admin2":"Al-Hasakeh",
    "admin3":"Markada",
    "location":"Al-Sa'da",
    "geo_precision":1,
    "source":"SHAM",
    "source_scale":"National",
    "notes":"On 27 May 2019, an IED planted in the village of Al-Sa'da by unidentified gunmen detonated as a QSD patrol was passing by, causing injuries and fatalities. Unknown number of fatalities coded to 10.",
    "fatalities":10,
    "timestamp":1567462247,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.4566,35.4454 ]
    },
    "properties": {
    "data_id":6046994,
    "iso":760,
    "event_id_cnty":"SYR61633",
    "event_id_no_cnty":61633,
    "event_date":"26 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Opposition Rebels (Syria)",
    "assoc_actor_1":"",
    "inter1":2,
    "actor2":"Militia (Pro-Government)",
    "assoc_actor_2":"",
    "inter2":3,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Hama",
    "admin2":"As-Suqaylabiyah",
    "admin3":"Madiq Castle",
    "location":"Tal Hawash",
    "geo_precision":2,
    "source":"SHAM; Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 26 May 2019, an unknown number of loyalist militia fighters were killed and wounded when they stepped on a landmine planted by rebel fighters in the Tal Hawash area. Fatalities coded to 10.",
    "fatalities":10,
    "timestamp":1571164400,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.6727,36.0139 ]
    },
    "properties": {
    "data_id":6046997,
    "iso":760,
    "event_id_cnty":"SYR61637",
    "event_id_no_cnty":61637,
    "event_date":"26 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"HTS: Hayat Tahrir al Sham",
    "assoc_actor_2":"",
    "inter2":2,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Idleb",
    "admin2":"Idleb",
    "admin3":"Maaret Tamsrin",
    "location":"Ma'arrat Tamasrin",
    "geo_precision":1,
    "source":"Liveuamap; SOHR",
    "source_scale":"Local partner-New media",
    "notes":"On 26 May 2019, an IED planted by unidentified gunmen in the vehicle of an HTS commander in the town of Ma'arrat Tamasrin detonated, killing the commander.",
    "fatalities":1,
    "timestamp":1571164400,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 39.0519,35.9428 ]
    },
    "properties": {
    "data_id":6046829,
    "iso":760,
    "event_id_cnty":"SYR61187",
    "event_id_no_cnty":61187,
    "event_date":"25 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":30,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Ar-Raqqa",
    "admin2":"Ar-Raqqa",
    "admin3":"Ar-Raqqa",
    "location":"Ar-Raqqa",
    "geo_precision":1,
    "source":"SOHR; Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 25 May 2019, an IED planted by unidentified gunmen exploded at the Al-Jazarah Junction near the Red Crescent building in the city of Ar-Raqqa, causing material damage. Neither injuries nor fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164400,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 40.0829,35.2035 ]
    },
    "properties": {
    "data_id":5672105,
    "iso":760,
    "event_id_cnty":"SYR61176",
    "event_id_no_cnty":61176,
    "event_date":"25 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Islamic State (Syria)",
    "assoc_actor_1":"",
    "inter1":2,
    "actor2":"Militia (Pro-Government)",
    "assoc_actor_2":"",
    "inter2":3,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Deir-ez-Zor",
    "admin2":"Deir-ez-Zor",
    "admin3":"Deir-ez-Zor",
    "location":"Al-Teem - Oil Field",
    "geo_precision":1,
    "source":"SOHR",
    "source_scale":"Other",
    "notes":"On 25 May 2019, a loyalist militia fighter was killed by a landmine planted by Islamic State fighters in the Al-Teem Oil Field.",
    "fatalities":1,
    "timestamp":1564753634,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.77,36.2125 ]
    },
    "properties": {
    "data_id":5672107,
    "iso":760,
    "event_id_cnty":"SYR61188",
    "event_id_no_cnty":61188,
    "event_date":"25 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":30,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Idleb",
    "admin2":"Harim",
    "admin3":"Dana",
    "location":"Dana",
    "geo_precision":1,
    "source":"SOHR",
    "source_scale":"Other",
    "notes":"On 25 May 2019, an IED planted by unidentified gunmen in the town of Dana detonated, causing material damage. Neither injuries nor fatalities were reported.",
    "fatalities":0,
    "timestamp":1564753634,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.7239,36.1866 ]
    },
    "properties": {
    "data_id":5672108,
    "iso":760,
    "event_id_cnty":"SYR61189",
    "event_id_no_cnty":61189,
    "event_date":"25 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":30,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Idleb",
    "admin2":"Harim",
    "admin3":"Dana",
    "location":"Sarmada",
    "geo_precision":1,
    "source":"SOHR",
    "source_scale":"Other",
    "notes":"On 25 May 2019, an IED planted by unidentified gunmen in the town of Sarmada detonated, causing material damage. Neither injuries nor fatalities were reported.",
    "fatalities":0,
    "timestamp":1564753634,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 40.9398,34.5734 ]
    },
    "properties": {
    "data_id":5672158,
    "iso":760,
    "event_id_cnty":"SYR61174",
    "event_id_no_cnty":61174,
    "event_date":"24 May 2019",
    "year":2019,
    "time_precision":2,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Islamic State (Syria)",
    "assoc_actor_1":"",
    "inter1":2,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":27,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Deir-ez-Zor",
    "admin2":"Abu Kamal",
    "admin3":"Susat",
    "location":"Shafa",
    "geo_precision":1,
    "source":"SOHR",
    "source_scale":"Other",
    "notes":"On 24 May 2019, a civilian succumbed to injuries received by an Islamic State landmine explosion in the town of Shafa a few days prior.",
    "fatalities":1,
    "timestamp":1564753634,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 40.1461,35.3319 ]
    },
    "properties": {
    "data_id":5672159,
    "iso":760,
    "event_id_cnty":"SYR61175",
    "event_id_no_cnty":61175,
    "event_date":"24 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Islamic State (Syria)",
    "assoc_actor_1":"",
    "inter1":2,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":27,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Deir-ez-Zor",
    "admin2":"Deir-ez-Zor",
    "admin3":"Deir-ez-Zor",
    "location":"Deir-ez-Zor",
    "geo_precision":2,
    "source":"SOHR",
    "source_scale":"Other",
    "notes":"On 24 May 2019, 4 children were killed and 11 civilians were wounded by a landmine planted by Islamic State fighters in the Adman area north of Deir-ez-Zor city.",
    "fatalities":4,
    "timestamp":1564753634,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 37.5149,36.3697 ]
    },
    "properties": {
    "data_id":6079148,
    "iso":760,
    "event_id_cnty":"SYR61183",
    "event_id_no_cnty":61183,
    "event_date":"23 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"JSH: Free Syrian Army",
    "assoc_actor_2":"",
    "inter2":2,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Aleppo",
    "admin2":"Al Bab",
    "admin3":"Al Bab",
    "location":"Al Bab",
    "geo_precision":1,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 23 May 2019, an FSA fighter was wounded by an IED placed in his car in the city of Al Bab by unidentified gunmen. No fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164581,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 38.0099,36.8145 ]
    },
    "properties": {
    "data_id":6046828,
    "iso":760,
    "event_id_cnty":"SYR61179",
    "event_id_no_cnty":61179,
    "event_date":"22 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Aleppo",
    "admin2":"Jarablus",
    "admin3":"Jarablus",
    "location":"Jarablus",
    "geo_precision":1,
    "source":"SOHR; Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On May 22, 2019, an IED attached to motorcycle by an unidentified armed group in Jarablus in eastern Aleppo countryside detonated wounding 2 women and 7 other individuals assumed to be civilians. No fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164400,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.1888,33.1461 ]
    },
    "properties": {
    "data_id":5672308,
    "iso":760,
    "event_id_cnty":"SYR61180",
    "event_id_no_cnty":61180,
    "event_date":"21 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Dar'a",
    "admin2":"As-Sanamayn",
    "admin3":"Ghabagheb",
    "location":"Deir al Bakht",
    "geo_precision":1,
    "source":"SOHR",
    "source_scale":"Other",
    "notes":"On 21 May, 2019, a landmine planted by an unidentified armed group in Deir al Bakht in northern Dar'a countryside detonated killing 1 child and wounding several others.",
    "fatalities":1,
    "timestamp":1564753634,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.3712,33.5643 ]
    },
    "properties": {
    "data_id":5672309,
    "iso":760,
    "event_id_cnty":"SYR61181",
    "event_id_no_cnty":61181,
    "event_date":"21 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Duma",
    "admin3":"Harasta",
    "location":"Harasta",
    "geo_precision":1,
    "source":"SOHR",
    "source_scale":"Other",
    "notes":"On 21 May, 2019, a landmine planted by an unidentified armed group in Harasta in Rural Damascus detonated killing 1 farmer.",
    "fatalities":1,
    "timestamp":1564753634,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 40.5376,35.2821 ]
    },
    "properties": {
    "data_id":6078923,
    "iso":760,
    "event_id_cnty":"SYR61186",
    "event_id_no_cnty":61186,
    "event_date":"21 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"QSD: Syrian Democratic Forces",
    "assoc_actor_2":"",
    "inter2":2,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Deir-ez-Zor",
    "admin2":"Deir-ez-Zor",
    "admin3":"Basira",
    "location":"Hejneh",
    "geo_precision":2,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On May 21, 2019, a VBIED planted by an unidentified armed group detonated in al Kashah area near Hejneh in southern Deir-ez-Zor countryside targeting a QSD vehicle and killing 2 members.",
    "fatalities":2,
    "timestamp":1571164581,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 37.0432,36.5849 ]
    },
    "properties": {
    "data_id":5672364,
    "iso":760,
    "event_id_cnty":"SYR61185",
    "event_id_no_cnty":61185,
    "event_date":"20 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Opposition Rebels (Syria)",
    "assoc_actor_2":"Former Operation Euphrates Shield",
    "inter2":2,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Aleppo",
    "admin2":"A'zaz",
    "admin3":"A'zaz",
    "location":"Azaz",
    "geo_precision":1,
    "source":"SOHR",
    "source_scale":"Other",
    "notes":"On 20 May 2019, an IED, planted by an unidentified armed group, targeted the vehicle of a commander of an opposition faction, which had operated under Operation Euphrates Shield, in the outskirts of Azaz in Aleppo. Explosion resulted in the killing of the commander.",
    "fatalities":1,
    "timestamp":1564753634,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 40.9398,34.5734 ]
    },
    "properties": {
    "data_id":6076167,
    "iso":760,
    "event_id_cnty":"SYR61182",
    "event_id_no_cnty":61182,
    "event_date":"19 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Deir-ez-Zor",
    "admin2":"Abu Kamal",
    "admin3":"Susat",
    "location":"Shafa",
    "geo_precision":1,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 19 May 2019, 1 civilian was killed following the explosion of landmine, previously planted by an unidentified armed group, in Shafa in Deir-ez-Zor.",
    "fatalities":1,
    "timestamp":1571164570,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 37.951,36.5258 ]
    },
    "properties": {
    "data_id":6046830,
    "iso":760,
    "event_id_cnty":"SYR61190",
    "event_id_no_cnty":61190,
    "event_date":"19 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":30,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Aleppo",
    "admin2":"Menbij",
    "admin3":"Menbij",
    "location":"Menbij",
    "geo_precision":1,
    "source":"Liveuamap; SOHR",
    "source_scale":"Local partner-New media",
    "notes":"On 19 May 2019, 2 IEDs, planted by an unidentified armed group, exploded near Al-Kura roundabout in Menbij in Aleppo, causing material damage. Neither injuries nor fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164400,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.7252,36.2963 ]
    },
    "properties": {
    "data_id":5672384,
    "iso":760,
    "event_id_cnty":"SYR61177",
    "event_id_no_cnty":61177,
    "event_date":"19 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"Refugees/IDPs (Syria)",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Idleb",
    "admin2":"Harim",
    "admin3":"Dana",
    "location":"Qah",
    "geo_precision":1,
    "source":"SOHR",
    "source_scale":"Other",
    "notes":"On 19 May 2019, an IED attached by an unidentified armed group to a vehicle exploded in Khan Shaykun Camp in Qah town in the northern countryside of Idleb, killing 2 civilians, including 1 child.",
    "fatalities":2,
    "timestamp":1564753634,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 37.5149,36.3697 ]
    },
    "properties": {
    "data_id":5672385,
    "iso":760,
    "event_id_cnty":"SYR61178",
    "event_id_no_cnty":61178,
    "event_date":"19 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Aleppo",
    "admin2":"Al Bab",
    "admin3":"Al Bab",
    "location":"Al Bab",
    "geo_precision":1,
    "source":"SOHR",
    "source_scale":"Other",
    "notes":"On 19 May 2019, a VBIED, planted by unidentified armed group, exploded near Al-Ihsan mosque in Al Bab in Aleppo, wounding 1 civilian. No fatalities were reported.",
    "fatalities":0,
    "timestamp":1564753634,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 39.0519,35.9428 ]
    },
    "properties": {
    "data_id":5672448,
    "iso":760,
    "event_id_cnty":"SYR60851",
    "event_id_no_cnty":60851,
    "event_date":"18 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Asayish (Syria)",
    "assoc_actor_2":"",
    "inter2":2,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Ar-Raqqa",
    "admin2":"Ar-Raqqa",
    "admin3":"Ar-Raqqa",
    "location":"Ar-Raqqa",
    "geo_precision":1,
    "source":"SOHR",
    "source_scale":"Other",
    "notes":"On 18 May 2019, an IED, planted by an unidentified armed group, targeted a passing Asayish vehicle near A-Jazra - Al-Panorama junction in the outskirts of Ar-Raqqa city, wounding 2 Asayish fighters. No fatalities were reported.",
    "fatalities":0,
    "timestamp":1564753634,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 40.4924,35.0574 ]
    },
    "properties": {
    "data_id":5672449,
    "iso":760,
    "event_id_cnty":"SYR60852",
    "event_id_no_cnty":60852,
    "event_date":"18 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"QSD: Syrian Democratic Forces",
    "assoc_actor_2":"",
    "inter2":2,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Deir-ez-Zor",
    "admin2":"Al Mayadin",
    "admin3":"Thiban",
    "location":"Al-Hawayij",
    "geo_precision":1,
    "source":"SOHR",
    "source_scale":"Other",
    "notes":"On 18 May 2019, an IED, planted by an unidentified armed group, targeted a QSD vehicle in Al-Hawayij village in Deir-ez-Zor. Neither injuries nor fatalities were reported.",
    "fatalities":0,
    "timestamp":1564753634,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.8655,36.5111 ]
    },
    "properties": {
    "data_id":5672458,
    "iso":760,
    "event_id_cnty":"SYR61184",
    "event_id_no_cnty":61184,
    "event_date":"18 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Opposition Rebels (Syria)",
    "assoc_actor_2":"Former Operation Euphrates Shield",
    "inter2":2,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Aleppo",
    "admin2":"Afrin",
    "admin3":"Afrin",
    "location":"Afrin",
    "geo_precision":1,
    "source":"SOHR",
    "source_scale":"Other",
    "notes":"On 18 May 2019, an IED, planted by an unidentified armed group, detonated targeting the vehicle of a commander of an opposition faction, which once operated under Euphrates Shield, in Al-Mahmudiyah neighborhood in Afrin in Aleppo. Neither injuries nor fatalities were reported.",
    "fatalities":0,
    "timestamp":1564753634,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.6884,36.3095 ]
    },
    "properties": {
    "data_id":6074859,
    "iso":760,
    "event_id_cnty":"SYR60902",
    "event_id_no_cnty":60902,
    "event_date":"18 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Idleb",
    "admin2":"Harim",
    "admin3":"Dana",
    "location":"Atmah",
    "geo_precision":2,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 18 May 2019, a roadside bomb, planted by unidentified armed group, exploded near Atmah town, along the Syrian-Turkish border, in the countryside of Idleb, killing 1 civilian and injuring 2 others.",
    "fatalities":1,
    "timestamp":1571164568,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.9771,35.9187 ]
    },
    "properties": {
    "data_id":5672505,
    "iso":760,
    "event_id_cnty":"SYR60901",
    "event_id_no_cnty":60901,
    "event_date":"17 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Aleppo",
    "admin2":"Jebel Saman",
    "admin3":"Zarbah",
    "location":"Huwair al-Eis",
    "geo_precision":1,
    "source":"SOHR",
    "source_scale":"Other",
    "notes":"On 17 May 2019, a child was killed following the explosion of a landmine, previously planted by an unidentified armed group, in Huwair al-Eis in the southern countryside of Aleppo.",
    "fatalities":1,
    "timestamp":1564753634,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 40.7429,36.5054 ]
    },
    "properties": {
    "data_id":5842154,
    "iso":760,
    "event_id_cnty":"SYR60850",
    "event_id_no_cnty":60850,
    "event_date":"17 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"QSD: Syrian Democratic Forces",
    "assoc_actor_2":"",
    "inter2":2,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Al-Hasakeh",
    "admin2":"Al-Hasakeh",
    "admin3":"Al-Hasakeh",
    "location":"Al-Hasakeh",
    "geo_precision":1,
    "source":"SHAM",
    "source_scale":"National",
    "notes":"On 17 May 2019, an IED planted by an unidentified armed group targeted a QSD patrol in al Nashwah neighborhood of al-Hasakeh city. Neither injuries nor fatalities were reported.",
    "fatalities":0,
    "timestamp":1567462247,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 37.951,36.5258 ]
    },
    "properties": {
    "data_id":6046720,
    "iso":760,
    "event_id_cnty":"SYR60848",
    "event_id_no_cnty":60848,
    "event_date":"16 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"QSD: Syrian Democratic Forces",
    "assoc_actor_2":"Menbij Military Council; Civilians (Syria)",
    "inter2":2,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Aleppo",
    "admin2":"Menbij",
    "admin3":"Menbij",
    "location":"Menbij",
    "geo_precision":1,
    "source":"Liveuamap; SOHR",
    "source_scale":"Local partner-New media",
    "notes":"On 16 May 2019, a VBIED planted by unidentified gunmen exploded near the headquarters of the Menbij Military Council in the al-Nadja neighborhood of the QSD-controlled city of Menbij, killing 1 and wounding at least 7 other people who are a mix of QSD and Menbij Military Council fighters and civilians.",
    "fatalities":1,
    "timestamp":1571164400,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 38.9548,36.6978 ]
    },
    "properties": {
    "data_id":5672543,
    "iso":760,
    "event_id_cnty":"SYR60847",
    "event_id_no_cnty":60847,
    "event_date":"16 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"QSD: Syrian Democratic Forces",
    "assoc_actor_2":"Asayish (Syria)",
    "inter2":2,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Ar-Raqqa",
    "admin2":"Tell Abiad",
    "admin3":"Tell Abiad",
    "location":"Tell Abiad",
    "geo_precision":2,
    "source":"SOHR",
    "source_scale":"Other",
    "notes":"On 16 May 2019, 3 QSD and Asayish fighters were killed by a series of landmines and IEDs planted in the Tell Abiad countryside by unidentified gunmen.",
    "fatalities":3,
    "timestamp":1564753634,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 40.7677,35.759 ]
    },
    "properties": {
    "data_id":5843560,
    "iso":760,
    "event_id_cnty":"SYR60849",
    "event_id_no_cnty":60849,
    "event_date":"16 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"QSD: Syrian Democratic Forces",
    "assoc_actor_2":"",
    "inter2":2,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Al-Hasakeh",
    "admin2":"Al-Hasakeh",
    "admin3":"Markada",
    "location":"Markada",
    "geo_precision":2,
    "source":"SHAM",
    "source_scale":"National",
    "notes":"On 16 May 2019, an IED planted by unidentified gunmen in the Markada area detonated as a QSD patrol passed by, wounding several QSD fighters. No fatalities were reported.",
    "fatalities":0,
    "timestamp":1567462249,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 37.5149,36.3697 ]
    },
    "properties": {
    "data_id":6076100,
    "iso":760,
    "event_id_cnty":"SYR60899",
    "event_id_no_cnty":60899,
    "event_date":"16 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Aleppo",
    "admin2":"Al Bab",
    "admin3":"Al Bab",
    "location":"Al Bab",
    "geo_precision":1,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 16 May 2019, a motorcycle with an IED planted by unidentified gunmen and parked in the city of Al Bab detonated, wounding several civilians. No fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164570,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 37.0432,36.5849 ]
    },
    "properties": {
    "data_id":6046727,
    "iso":760,
    "event_id_cnty":"SYR60897",
    "event_id_no_cnty":60897,
    "event_date":"15 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Aleppo",
    "admin2":"A'zaz",
    "admin3":"A'zaz",
    "location":"Azaz",
    "geo_precision":2,
    "source":"SOHR; Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 15 May 2019, an IED attached to a motorcycle by unidentified gunmen and parked in Sejju roundabout north of the city of Azaz detonated, wounding 5 civilians. No fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164400,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 38.9548,36.6978 ]
    },
    "properties": {
    "data_id":6074878,
    "iso":760,
    "event_id_cnty":"SYR60896",
    "event_id_no_cnty":60896,
    "event_date":"15 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Ar-Raqqa",
    "admin2":"Tell Abiad",
    "admin3":"Tell Abiad",
    "location":"Tell Abiad",
    "geo_precision":1,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 15 May 2019, a civilian was wounded by a landmine planted by unidentified gunmen in the town of Tell Abiad. No fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164568,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 37.1524,36.206 ]
    },
    "properties": {
    "data_id":6076812,
    "iso":760,
    "event_id_cnty":"SYR60883",
    "event_id_no_cnty":60883,
    "event_date":"14 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":30,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Aleppo",
    "admin2":"Jebel Saman",
    "admin3":"Jebel Saman",
    "location":"Aleppo",
    "geo_precision":1,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 14 May 2019, an explosion of an unknown nature was heard near a municipal building in the city of Aleppo with neither injuries nor fatalities reported.",
    "fatalities":0,
    "timestamp":1571164570,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 40.7429,36.5054 ]
    },
    "properties": {
    "data_id":5843436,
    "iso":760,
    "event_id_cnty":"SYR60882",
    "event_id_no_cnty":60882,
    "event_date":"14 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":30,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Al-Hasakeh",
    "admin2":"Al-Hasakeh",
    "admin3":"Al-Hasakeh",
    "location":"Al-Hasakeh",
    "geo_precision":1,
    "source":"SHAM",
    "source_scale":"National",
    "notes":"On 14 May 2019, an explosion of an unknown nature was heard in the town of Al-Hasakeh. Neither injuries nor fatalities were reported.",
    "fatalities":0,
    "timestamp":1567462248,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 39.008,35.9504 ]
    },
    "properties": {
    "data_id":6046724,
    "iso":760,
    "event_id_cnty":"SYR60880",
    "event_id_no_cnty":60880,
    "event_date":"13 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":30,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Ar-Raqqa",
    "admin2":"Ar-Raqqa",
    "admin3":"Ar-Raqqa",
    "location":"Ar-Raqqa - Amin",
    "geo_precision":1,
    "source":"Liveuamap; SOHR",
    "source_scale":"Local partner-New media",
    "notes":"On 13 May, 2019, an IED planted by an unidentified armed group in al Fardos area in Amin neighborhood of Ar-Raqqa city detonated. Neither fatalities nor injuries were reported.",
    "fatalities":0,
    "timestamp":1571164400,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 38.9987,35.9613 ]
    },
    "properties": {
    "data_id":5672708,
    "iso":760,
    "event_id_cnty":"SYR60846",
    "event_id_no_cnty":60846,
    "event_date":"13 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"QSD: Syrian Democratic Forces",
    "assoc_actor_2":"",
    "inter2":2,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Ar-Raqqa",
    "admin2":"Ar-Raqqa",
    "admin3":"Ar-Raqqa",
    "location":"Ar-Raqqa - Wihdeh",
    "geo_precision":1,
    "source":"SOHR",
    "source_scale":"Other",
    "notes":"On 13 May, 2019, an IED planted by an unidentified armed group near al Bayda'a park in Wihdeh neighborhood in Ar-Raqqa city detonated targeting a QSD vehicle and causing material damages. Neither fatalities nor injuries were reported.",
    "fatalities":0,
    "timestamp":1564753634,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.7239,36.1866 ]
    },
    "properties": {
    "data_id":5672711,
    "iso":760,
    "event_id_cnty":"SYR60881",
    "event_id_no_cnty":60881,
    "event_date":"13 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":30,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Idleb",
    "admin2":"Harim",
    "admin3":"Dana",
    "location":"Sarmada",
    "geo_precision":1,
    "source":"SOHR",
    "source_scale":"Other",
    "notes":"On 13 May, 2019, an IED planted by an unidentified armed group on the outskirts of Sarmada in northern Idleb countryside detonated. Neither fatalities nor injuries were reported.",
    "fatalities":0,
    "timestamp":1564753634,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.3489,35.5731 ]
    },
    "properties": {
    "data_id":6077725,
    "iso":760,
    "event_id_cnty":"SYR60823",
    "event_id_no_cnty":60823,
    "event_date":"13 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Opposition Rebels (Syria)",
    "assoc_actor_1":"",
    "inter1":2,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":20,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Hama",
    "admin2":"As-Suqaylabiyah",
    "admin3":"Madiq Castle",
    "location":"Jisr Beit Ras",
    "geo_precision":2,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"Detonation: On 13 May, 2019, opposition forces detonated a bridge near Jisr Beit Ras separating their held areas in said town with the regime's in Hama countryside.",
    "fatalities":0,
    "timestamp":1571164572,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.7914,35.6746 ]
    },
    "properties": {
    "data_id":6077127,
    "iso":760,
    "event_id_cnty":"SYR60845",
    "event_id_no_cnty":60845,
    "event_date":"13 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"JTW: National Liberation Front",
    "assoc_actor_2":"",
    "inter2":2,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Idleb",
    "admin2":"Al Ma'ra",
    "admin3":"Ma'arrat An Nu'man",
    "location":"Ghadqa",
    "geo_precision":1,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 13 May, 2019, an IED planted by an unidentified armed group in Ghadqa in southern Idleb countryside detonated targeting a JTW commander's vehicle and killing him.",
    "fatalities":1,
    "timestamp":1571164571,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.7828,35.6182 ]
    },
    "properties": {
    "data_id":5672732,
    "iso":760,
    "event_id_cnty":"SYR60843",
    "event_id_no_cnty":60843,
    "event_date":"12 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Jaysh al Ahrar",
    "assoc_actor_2":"",
    "inter2":2,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Idleb",
    "admin2":"Al Ma'ra",
    "admin3":"Ma'arrat An Nu'man",
    "location":"Jarjnaz",
    "geo_precision":2,
    "source":"SOHR",
    "source_scale":"Other",
    "notes":"On 12 May, 2019, a roadside IED planted by an unidentified armed group on Ghadqa - Jarjnaz road in southern Idleb countryside detonated targeting a Jaysh al Ahrar vehicle, killing 1 commander and wounding several other members.",
    "fatalities":1,
    "timestamp":1564753634,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 40.7268,36.0534 ]
    },
    "properties": {
    "data_id":5842848,
    "iso":760,
    "event_id_cnty":"SYR60844",
    "event_id_no_cnty":60844,
    "event_date":"12 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"YPG: Peoples Protection Units",
    "assoc_actor_2":"",
    "inter2":2,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Al-Hasakeh",
    "admin2":"Al-Hasakeh",
    "admin3":"Shadadah",
    "location":"Shadadah",
    "geo_precision":1,
    "source":"SHAM",
    "source_scale":"National",
    "notes":"On 12 May, 2019, an IED planted by an unidentified armed group detonated near a Syriatel telecommunications tower in Shadadah in southern al-Hasakeh countryside, wounding 1 YPG members. No fatalities were reported.",
    "fatalities":0,
    "timestamp":1567462248,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 38.5364,35.8308 ]
    },
    "properties": {
    "data_id":6078442,
    "iso":760,
    "event_id_cnty":"SYR60891",
    "event_id_no_cnty":60891,
    "event_date":"12 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Militia (Pro-Government)",
    "assoc_actor_2":"",
    "inter2":3,
    "interaction":33,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Ar-Raqqa",
    "admin2":"Ath-Thawrah",
    "admin3":"Al-Thawrah",
    "location":"Al Tabqa",
    "geo_precision":2,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 12 May, 2019, a roadside IED planted by an unidentified armed group south of al Tabqa in western Ar-Raqqa countryside detonated targeting a pro-regime militia forces vehicle, killing 2 and wounding 1.",
    "fatalities":2,
    "timestamp":1571164574,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 40.6618,35.5066 ]
    },
    "properties": {
    "data_id":6046520,
    "iso":760,
    "event_id_cnty":"SYR60361",
    "event_id_no_cnty":60361,
    "event_date":"11 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"QSD: Syrian Democratic Forces",
    "assoc_actor_2":"",
    "inter2":2,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Deir-ez-Zor",
    "admin2":"Deir-ez-Zor",
    "admin3":"Sur",
    "location":"Sur",
    "geo_precision":1,
    "source":"Liveuamap; SOHR",
    "source_scale":"Local partner-New media",
    "notes":"On 11 May, 2019, an IED attached to a motorcycle by an unidentified armed group detonated in Sur in southern Deir-ez-Zor countryside wounding several QSD members. No fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164400,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 40.4263,35.2012 ]
    },
    "properties": {
    "data_id":5672766,
    "iso":760,
    "event_id_cnty":"SYR60360",
    "event_id_no_cnty":60360,
    "event_date":"11 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"QSD: Syrian Democratic Forces",
    "assoc_actor_2":"Civilians (Syria)",
    "inter2":2,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Deir-ez-Zor",
    "admin2":"Deir-ez-Zor",
    "admin3":"Basira",
    "location":"Al Sabkhah",
    "geo_precision":1,
    "source":"SOHR",
    "source_scale":"Other",
    "notes":"On 11 May, 2019, a roadside IED planted by an unidentified armed group on the outskirts of al Sabkha in southern Deir-ez-Zor countryside detonated targeting a QSD column carrying fuel supplies, wounding 1 individual, assumed to be civilian, and set fire to one of the fuel tankers. No fatalities were reported.",
    "fatalities":0,
    "timestamp":1564753634,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.3561,33.4338 ]
    },
    "properties": {
    "data_id":5672768,
    "iso":760,
    "event_id_cnty":"SYR60411",
    "event_id_no_cnty":60411,
    "event_date":"11 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Rural Damascus",
    "admin2":"Rural Damascus",
    "admin3":"Jaramana",
    "location":"Bahdaliyah",
    "geo_precision":1,
    "source":"SOHR",
    "source_scale":"Other",
    "notes":"On 11 May, 2019, a landmine planted by an unidentified armed group detonated in Bahdaliyah in Rural Damascus killing 1 child and wounding at least 2 others.",
    "fatalities":1,
    "timestamp":1564753634,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.3005,33.4854 ]
    },
    "properties": {
    "data_id":6046536,
    "iso":760,
    "event_id_cnty":"SYR60412",
    "event_id_no_cnty":60412,
    "event_date":"11 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Damascus",
    "admin2":"Damascus",
    "admin3":"Damascus",
    "location":"Damascus - Al-Midan",
    "geo_precision":1,
    "source":"Liveuamap; SOHR",
    "source_scale":"Local partner-New media",
    "notes":"On 11 May, 2019, a VBIED planted by an unidentified armed group detonated in al Zahira neighborhood in the al Midan area of Damascus city, wounding 11 individuals assumed to be civilian. No fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164400,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 40.8392,34.6869 ]
    },
    "properties": {
    "data_id":6079926,
    "iso":760,
    "event_id_cnty":"SYR60362",
    "event_id_no_cnty":60362,
    "event_date":"11 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"QSD: Syrian Democratic Forces",
    "assoc_actor_2":"",
    "inter2":2,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Deir-ez-Zor",
    "admin2":"Abu Kamal",
    "admin3":"Hajin",
    "location":"Hajin",
    "geo_precision":1,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 11 May, 2019, an IED planted by an unidentified armed group in Hajin in southern Deir-ez-Zor countryside detonated targeting a QSD patrol. Neither fatalities nor injuries were reported.",
    "fatalities":0,
    "timestamp":1571164582,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 40.4543,35.092 ]
    },
    "properties": {
    "data_id":5672818,
    "iso":760,
    "event_id_cnty":"SYR60393",
    "event_id_no_cnty":60393,
    "event_date":"10 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":30,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Deir-ez-Zor",
    "admin2":"Deir-ez-Zor",
    "admin3":"Basira",
    "location":"Shiheil",
    "geo_precision":1,
    "source":"SOHR",
    "source_scale":"Other",
    "notes":"On 10 May, 2019, an IED planted by an unidentified armed group detonated in Shiheil in southern Deir-ez-Zor countryside at a former QSD command center. Neither fatalities nor injuries were reported.",
    "fatalities":0,
    "timestamp":1564753635,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.1049,32.6241 ]
    },
    "properties": {
    "data_id":6046532,
    "iso":760,
    "event_id_cnty":"SYR60403",
    "event_id_no_cnty":60403,
    "event_date":"08 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Unidentified Armed Group (Syria)",
    "assoc_actor_2":"Former Free Syrian Police (Syria); Civilians (Syria)",
    "inter2":3,
    "interaction":33,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Dar'a",
    "admin2":"Dar'a",
    "admin3":"Dar'a",
    "location":"Dar'a",
    "geo_precision":1,
    "source":"Liveuamap; SOHR",
    "source_scale":"Local partner-New media",
    "notes":"On 08 May 2019, an IED, planted by an unidentified armed group, targeted the vehicle of the former Free Syrian Police commander in Dar'a al-Balad, in Dar'a al-Balad in Dar'a city, killing the commander and another person.",
    "fatalities":2,
    "timestamp":1571164400,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 37.951,36.5258 ]
    },
    "properties": {
    "data_id":6046534,
    "iso":760,
    "event_id_cnty":"SYR60409",
    "event_id_no_cnty":60409,
    "event_date":"08 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Aleppo",
    "admin2":"Menbij",
    "admin3":"Menbij",
    "location":"Menbij",
    "geo_precision":2,
    "source":"SOHR; Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 08 May 2019, a booby trapped motorcycle detonated in Al-Farat village in the western countryside of Menbij in Aleppo, killing 2 people and injuring 4 others.",
    "fatalities":2,
    "timestamp":1571164400,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 40.7429,36.5054 ]
    },
    "properties": {
    "data_id":5841512,
    "iso":760,
    "event_id_cnty":"SYR60359",
    "event_id_no_cnty":60359,
    "event_date":"08 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"QSD: Syrian Democratic Forces",
    "assoc_actor_2":"",
    "inter2":2,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Al-Hasakeh",
    "admin2":"Al-Hasakeh",
    "admin3":"Al-Hasakeh",
    "location":"Al-Hasakeh",
    "geo_precision":3,
    "source":"SHAM",
    "source_scale":"National",
    "notes":"On 08 May 2019, an IED, planted by an unidentified armed group, targeted a QSD patrol near Al-Attala village in Al-Hasakeh. Neither injuries nor fatalities were reported.",
    "fatalities":0,
    "timestamp":1567462246,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.6893,35.3739 ]
    },
    "properties": {
    "data_id":5840772,
    "iso":760,
    "event_id_cnty":"SYR60408",
    "event_id_no_cnty":60408,
    "event_date":"08 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"Farmers (Syria)",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Hama",
    "admin2":"Hama",
    "admin3":"Suran",
    "location":"Murak",
    "geo_precision":2,
    "source":"SHAM",
    "source_scale":"National",
    "notes":"On 08 May 2019, 2 young farmers were killed following the explosion of a landmine, planted by an unidentified armed group, in the farmlands surrounding Murak town in Hama.",
    "fatalities":2,
    "timestamp":1567462245,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 37.951,36.5258 ]
    },
    "properties": {
    "data_id":6078900,
    "iso":760,
    "event_id_cnty":"SYR60410",
    "event_id_no_cnty":60410,
    "event_date":"08 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Aleppo",
    "admin2":"Menbij",
    "admin3":"Menbij",
    "location":"Menbij",
    "geo_precision":2,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 08 May 2019, a roadside IED, planted by an unidentified armed group, exploded near a QSD checkpoint on the 4th KM north of Menbij city in Aleppo, killing 3 children.",
    "fatalities":3,
    "timestamp":1571164581,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 39.0519,35.9428 ]
    },
    "properties": {
    "data_id":6075890,
    "iso":760,
    "event_id_cnty":"SYR60405",
    "event_id_no_cnty":60405,
    "event_date":"08 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Kurdish Ethnic Militia (Syria)",
    "assoc_actor_2":"",
    "inter2":4,
    "interaction":34,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Ar-Raqqa",
    "admin2":"Ar-Raqqa",
    "admin3":"Ar-Raqqa",
    "location":"Ar-Raqqa",
    "geo_precision":2,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 08 May 2019, an IED, planted by an unidentified armed group, targeted the headquarters of a Kurdish militia near Kasra Sheikh Al-Juma'a village south-west of Ar-Raqqa city, killing and wounding an unknown number of Kurdish militia fighters. Unknown number of fatalities coded as 10.",
    "fatalities":10,
    "timestamp":1571164569,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 39.0519,35.9428 ]
    },
    "properties": {
    "data_id":6075674,
    "iso":760,
    "event_id_cnty":"SYR60396",
    "event_id_no_cnty":60396,
    "event_date":"07 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":30,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Ar-Raqqa",
    "admin2":"Ar-Raqqa",
    "admin3":"Ar-Raqqa",
    "location":"Ar-Raqqa",
    "geo_precision":2,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 7 May 2019, an explosion of an unknown nature occurred south of the city of Ar-Raqqa near a bridge. Neither injuries nor fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164569,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 40.6939,34.8116 ]
    },
    "properties": {
    "data_id":6046533,
    "iso":760,
    "event_id_cnty":"SYR60407",
    "event_id_no_cnty":60407,
    "event_date":"07 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"Health Workers (Syria)",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Deir-ez-Zor",
    "admin2":"Abu Kamal",
    "admin3":"Hajin",
    "location":"Kishkiyeh",
    "geo_precision":1,
    "source":"Liveuamap; SOHR",
    "source_scale":"Local partner-New media",
    "notes":"On 07 May 2019, a booby trapped motorcycle detonated in front of Kishkiyeh town hospital in the eastern countryside of Der-e-Zor, killing 1 person and injuring 3 others.",
    "fatalities":1,
    "timestamp":1571164400,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 37.951,36.5258 ]
    },
    "properties": {
    "data_id":6046538,
    "iso":760,
    "event_id_cnty":"SYR60415",
    "event_id_no_cnty":60415,
    "event_date":"07 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Aleppo",
    "admin2":"Menbij",
    "admin3":"Menbij",
    "location":"Menbij",
    "geo_precision":1,
    "source":"SOHR; Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 7 May 2019, a booby-trapped motorcycle parked by an unidentified armed group on 30th street in the city of Menbij exploded, causing material damage and wounding a child. No fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164400,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 40.4543,35.092 ]
    },
    "properties": {
    "data_id":6076762,
    "iso":760,
    "event_id_cnty":"SYR60364",
    "event_id_no_cnty":60364,
    "event_date":"07 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"QSD: Syrian Democratic Forces",
    "assoc_actor_2":"",
    "inter2":2,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Deir-ez-Zor",
    "admin2":"Deir-ez-Zor",
    "admin3":"Basira",
    "location":"Shiheil",
    "geo_precision":1,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 7 May 2019, an IED planted by an unidentified armed group exploded in an irrigation ditch near a QSD checkpoint in the town of Shiheil with neither injuries nor fatalities reported.",
    "fatalities":0,
    "timestamp":1571164570,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 40.7677,35.759 ]
    },
    "properties": {
    "data_id":5839769,
    "iso":760,
    "event_id_cnty":"SYR60363",
    "event_id_no_cnty":60363,
    "event_date":"07 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"QSD: Syrian Democratic Forces",
    "assoc_actor_2":"",
    "inter2":2,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Al-Hasakeh",
    "admin2":"Al-Hasakeh",
    "admin3":"Markada",
    "location":"Markada",
    "geo_precision":2,
    "source":"SHAM",
    "source_scale":"National",
    "notes":"On 7 May 2019, a QSD fighter was killed by a landmine planted by an unidentified armed group near the town of Markada.",
    "fatalities":1,
    "timestamp":1567462244,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.6353,35.929 ]
    },
    "properties": {
    "data_id":6046526,
    "iso":760,
    "event_id_cnty":"SYR60395",
    "event_id_no_cnty":60395,
    "event_date":"06 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":30,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Idleb",
    "admin2":"Idleb",
    "admin3":"Idleb",
    "location":"Idleb",
    "geo_precision":1,
    "source":"SOHR; Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 6 May 2019, an explosion of an unknown nature was hear near the Saad mosque in the city of Idleb. Neither injuries nor fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164400,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 37.5663,36.4337 ]
    },
    "properties": {
    "data_id":6046537,
    "iso":760,
    "event_id_cnty":"SYR60414",
    "event_id_no_cnty":60414,
    "event_date":"06 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Aleppo",
    "admin2":"Al Bab",
    "admin3":"Al Bab",
    "location":"Qabasin",
    "geo_precision":1,
    "source":"SOHR; Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 6 May 2019, an IED attached to a motorcycle by an unidentified armed group in the town of Qabasin detonated, wounding at least 8 civilians. No fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164400,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 40.7665,34.982 ]
    },
    "properties": {
    "data_id":6078548,
    "iso":760,
    "event_id_cnty":"SYR60394",
    "event_id_no_cnty":60394,
    "event_date":"06 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":30,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Deir-ez-Zor",
    "admin2":"Al Mayadin",
    "admin3":"Al Mayadin",
    "location":"Omar - Oil Fields",
    "geo_precision":2,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 6 May 2019, a large explosion of an unknown nature was heard along the road to the Omar Oil Field in Deir-ez-Zor province with neither injuries nor fatalities reported.",
    "fatalities":0,
    "timestamp":1571164574,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.2542,32.8677 ]
    },
    "properties": {
    "data_id":6082104,
    "iso":760,
    "event_id_cnty":"SYR60404",
    "event_id_no_cnty":60404,
    "event_date":"05 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Militia (Pro-Government)",
    "assoc_actor_2":"",
    "inter2":3,
    "interaction":33,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Dar'a",
    "admin2":"Izra'",
    "admin3":"Izra'",
    "location":"Izra'",
    "geo_precision":2,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 5 May 2019, an unknown number of loyalist militia fighters were killed when their vehicle was targeted by a roadside IED planted by an unidentified armed group as it traveled along the road between Izra' and Basra al-Hariri. Unknown fatalities coded to 10.",
    "fatalities":10,
    "timestamp":1571164585,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.1965,32.5837 ]
    },
    "properties": {
    "data_id":5673086,
    "iso":760,
    "event_id_cnty":"SYR60271",
    "event_id_no_cnty":60271,
    "event_date":"05 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Military Forces of Syria (2000-) Syrian Arab Air Force",
    "assoc_actor_2":"",
    "inter2":1,
    "interaction":13,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Dar'a",
    "admin2":"Dar'a",
    "admin3":"Dar'a",
    "location":"Um Elmayathen",
    "geo_precision":1,
    "source":"SOHR",
    "source_scale":"Other",
    "notes":"On 5 May 2019, an IED placed by an unidentified armed group near the home of a brigadier general in the Syrian Air Force in the town of Um Elmayathen detonated, causing material damage. Neither injuries nor fatalities were reported.",
    "fatalities":0,
    "timestamp":1564753635,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 37.951,36.5258 ]
    },
    "properties": {
    "data_id":6081781,
    "iso":760,
    "event_id_cnty":"SYR60413",
    "event_id_no_cnty":60413,
    "event_date":"05 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Aleppo",
    "admin2":"Menbij",
    "admin3":"Menbij",
    "location":"Menbij",
    "geo_precision":1,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 5 May 2019, 3 children were wounded by an IED placed by an unidentified armed group in a car near an oven in the city of Menbij. No fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164584,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 40.0862,35.4429 ]
    },
    "properties": {
    "data_id":6081124,
    "iso":760,
    "event_id_cnty":"SYR59888",
    "event_id_no_cnty":59888,
    "event_date":"04 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"QSD: Syrian Democratic Forces",
    "assoc_actor_2":"",
    "inter2":2,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Deir-ez-Zor",
    "admin2":"Deir-ez-Zor",
    "admin3":"Kisreh",
    "location":"Mhemideh",
    "geo_precision":1,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 4 May 2019, an IED planted by unidentified gunmen in the town of Mhemideh detonated, wounding several QSD fighters. No fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164583,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 40.9677,34.5249 ]
    },
    "properties": {
    "data_id":6078097,
    "iso":760,
    "event_id_cnty":"SYR59884",
    "event_id_no_cnty":59884,
    "event_date":"04 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Deir-ez-Zor",
    "admin2":"Abu Kamal",
    "admin3":"Susat",
    "location":"Sosa",
    "geo_precision":1,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 4 May 2019, 2 civilians were killed when they stepped on a landmine planted by unidentifed armed group in the town of Sosa.",
    "fatalities":2,
    "timestamp":1571164574,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 40.7429,36.5054 ]
    },
    "properties": {
    "data_id":5841968,
    "iso":760,
    "event_id_cnty":"SYR59890",
    "event_id_no_cnty":59890,
    "event_date":"03 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":30,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Al-Hasakeh",
    "admin2":"Al-Hasakeh",
    "admin3":"Al-Hasakeh",
    "location":"Al-Hasakeh",
    "geo_precision":1,
    "source":"SHAM",
    "source_scale":"National",
    "notes":"On 3 May 2019, a loud explosion was heard in the al-Aziziyah neighborhood of Al-Hasakeh city with neither injuries nor fatalities reported.",
    "fatalities":0,
    "timestamp":1567462247,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 39.0292,35.9631 ]
    },
    "properties": {
    "data_id":6079550,
    "iso":760,
    "event_id_cnty":"SYR59892",
    "event_id_no_cnty":59892,
    "event_date":"03 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":30,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Ar-Raqqa",
    "admin2":"Ar-Raqqa",
    "admin3":"Ar-Raqqa",
    "location":"Ar-Raqqa - Tishrine",
    "geo_precision":1,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 3 May 2019, an explosion of an unknown nature occurred in Tishrine neighborhood in the city of Ar-Raqqa with neither injuries nor fatalities reported.",
    "fatalities":0,
    "timestamp":1571164581,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 37.7556,36.6771 ]
    },
    "properties": {
    "data_id":6077739,
    "iso":760,
    "event_id_cnty":"SYR59893",
    "event_id_no_cnty":59893,
    "event_date":"02 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":30,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Aleppo",
    "admin2":"Jarablus",
    "admin3":"Ghandorah",
    "location":"Ghandorah",
    "geo_precision":1,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 2 May 2019, an unidentifed armed group attached an IED to a motorcycle in the town of Ghandorah detonated with neither injuries nor fatalities reported.",
    "fatalities":0,
    "timestamp":1571164572,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 40.1461,35.3319 ]
    },
    "properties": {
    "data_id":5673288,
    "iso":760,
    "event_id_cnty":"SYR59882",
    "event_id_no_cnty":59882,
    "event_date":"02 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Deir-ez-Zor",
    "admin2":"Deir-ez-Zor",
    "admin3":"Deir-ez-Zor",
    "location":"Deir-ez-Zor",
    "geo_precision":3,
    "source":"SOHR",
    "source_scale":"Other",
    "notes":"On 2 May 2019, an IED planted by unidentified armed group in a vehicle of a civilian who trades in oil with QSD forces in the village of Al-Raz in Deir-ez-Zor province detonated with neither injuries nor fatalities reported.",
    "fatalities":0,
    "timestamp":1564753635,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 40.0747,36.8494 ]
    },
    "properties": {
    "data_id":6078100,
    "iso":760,
    "event_id_cnty":"SYR59880",
    "event_id_no_cnty":59880,
    "event_date":"02 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Asayish (Syria)",
    "assoc_actor_2":"",
    "inter2":2,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Al-Hasakeh",
    "admin2":"Ras Al Ain",
    "admin3":"Ras Al Ain",
    "location":"Ras Al Ain",
    "geo_precision":2,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 2 May 2019, 3 Asayish fighters were wounded by a landmine explosion in the road from Ras al Ain to the village of Abu Rasin. No fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164574,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 39.0519,35.9428 ]
    },
    "properties": {
    "data_id":6082365,
    "iso":760,
    "event_id_cnty":"SYR59891",
    "event_id_no_cnty":59891,
    "event_date":"01 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":30,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Ar-Raqqa",
    "admin2":"Ar-Raqqa",
    "admin3":"Ar-Raqqa",
    "location":"Ar-Raqqa",
    "geo_precision":1,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 1 May, 2019, an unknown explosion occurred in Ar-Raqqa city. Neither fatalities nor injuries were reported.",
    "fatalities":0,
    "timestamp":1571164585,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 38.0099,36.8145 ]
    },
    "properties": {
    "data_id":6080339,
    "iso":760,
    "event_id_cnty":"SYR59894",
    "event_id_no_cnty":59894,
    "event_date":"01 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"",
    "assoc_actor_2":"",
    "inter2":0,
    "interaction":30,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Aleppo",
    "admin2":"Jarablus",
    "admin3":"Jarablus",
    "location":"Jarablus",
    "geo_precision":1,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 1 May, 2019, an unidentifed armed group attached an IED to a motorcycle by an unidentified armed group on the outskirts of Jarablus in eastern Aleppo countryside detonated. Neither fatalities nor injuries were reported.",
    "fatalities":0,
    "timestamp":1571164582,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 37.951,36.5258 ]
    },
    "properties": {
    "data_id":6046341,
    "iso":760,
    "event_id_cnty":"SYR59876",
    "event_id_no_cnty":59876,
    "event_date":"01 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Islamic State (Syria)",
    "assoc_actor_1":"",
    "inter1":2,
    "actor2":"JaT: Army of Revolutionaries",
    "assoc_actor_2":"",
    "inter2":2,
    "interaction":22,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Aleppo",
    "admin2":"Menbij",
    "admin3":"Menbij",
    "location":"Menbij",
    "geo_precision":1,
    "source":"Liveuamap; SOHR",
    "source_scale":"Local partner-New media",
    "notes":"On 1 May, 2019, an IED planted by IS near al Kitab roundabout in Menbij city in eastern Aleppo countryside detonated targeting a JaT commander, wounding the target and 2 of his escorts. No fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164400,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 37.5149,36.3697 ]
    },
    "properties": {
    "data_id":6046344,
    "iso":760,
    "event_id_cnty":"SYR59885",
    "event_id_no_cnty":59885,
    "event_date":"01 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"JWS: Syrian National Army",
    "assoc_actor_2":"Civilians (Syria)",
    "inter2":2,
    "interaction":23,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Aleppo",
    "admin2":"Al Bab",
    "admin3":"Al Bab",
    "location":"Al Bab",
    "geo_precision":1,
    "source":"SOHR; Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 1 May, 2019, a roadside IED planted by an unidentified armed group in al Bab city in eastern Aleppo countryside detonated targeting a JWS vehicle, wounding several civilians. No fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164400,
    "iso3":"SYR"
    }
  },
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 36.7239,36.1866 ]
    },
    "properties": {
    "data_id":6081424,
    "iso":760,
    "event_id_cnty":"SYR59883",
    "event_id_no_cnty":59883,
    "event_date":"01 May 2019",
    "year":2019,
    "time_precision":1,
    "event_type":"Explosions/Remote violence",
    "sub_event_type":"Remote explosive/landmine/IED",
    "actor1":"Unidentified Armed Group (Syria)",
    "assoc_actor_1":"",
    "inter1":3,
    "actor2":"Civilians (Syria)",
    "assoc_actor_2":"",
    "inter2":7,
    "interaction":37,
    "region":"Middle East",
    "country":"Syria",
    "admin1":"Idleb",
    "admin2":"Harim",
    "admin3":"Dana",
    "location":"Sarmada",
    "geo_precision":1,
    "source":"Liveuamap",
    "source_scale":"Local partner-New media",
    "notes":"On 1 May, 2019, an IED planted by an unidentified armed group on the entrance of Sarmada in northern Idleb countryside detonated wounding 2 individuals assumed to be civilian. No fatalities were reported.",
    "fatalities":0,
    "timestamp":1571164584,
    "iso3":"SYR"
    }
  }
]
}